name: run main.py

on:
  push:
    branches:
  schedule:     
    - cron: '0 11 * * *'

on: push

jobs:
  scrape-website:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write


    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' 
          
      - name: poetry setup
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.4.0
          
      - name: install dependencies
        run: poetry install

      - name: execute py script 
        run: poetry run python main.py

      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4